import json
import xml.etree.ElementTree as ET

from bpmn_assistant.config import logger
from bpmn_assistant.services import BpmnProcessTransformer


class BpmnXmlGenerator:
    """
    Class to generate BPMN XML from the BPMN process data in JSON format.
    """

    def __init__(self):
        self.transformer = BpmnProcessTransformer()

    def create_bpmn_xml(self, process: list[dict]) -> str:
        """
        Create BPMN XML from the process data.
        Args:
            process: BPMN process structure generated by the LLM.
            The BPMN XML string.
        """

        logger.info('create_bpmn_xml enter')

        transformed_process = self.transformer.transform(process)
        logger.debug(
            f"Transformed process:\n{json.dumps(transformed_process, indent=2)}"
        )

        # Create the root element (definitions)
        root = ET.Element("definitions")
        root.set("xmlns", "http://www.omg.org/spec/BPMN/20100524/MODEL")
        root.set("xmlns:bpmndi", "http://www.omg.org/spec/BPMN/20100524/DI")
        root.set("xmlns:dc", "http://www.omg.org/spec/DD/20100524/DC")
        root.set("xmlns:di", "http://www.omg.org/spec/DD/20100524/DI")
        root.set("xmlns:flowable", "http://flowable.org/bpmn")
        root.set("id", "definitions_1")

        # Create the process element
        process_element = ET.SubElement(root, "process")
        process_element.set("id", "Process_1")
        process_element.set("isExecutable", "false")

        # Add elements
        for element in transformed_process["elements"]:
            elem = ET.SubElement(process_element, element["type"])
            elem.set("id", element["id"])

            # Add label if it exists
            if "label" in element and element["label"]:
                elem.set("name", element["label"])

            # Add default flow attribute for inclusive/exclusive gateways if it exists
            if "default_flow" in element and element["default_flow"]:
                elem.set("default", element["default_flow"])

            if "variables" in element and element["variables"]:
                for elpar in element["variables"]:
                    print('VARIABLES', elpar)
                    # TODO permissions ?
                    extension_el = ET.SubElement(elem, "bpmn:extensionElements")
                    form_el = ET.SubElement(extension_el, "flowable:formProperty")
                    if 'type' in elpar and 'id' in elpar: 
                        var_el = ET.SubElement(form_el, "flowable:value")
                        var_el.set('id', elpar['id'])
                        var_el.set('name', elpar['id'])
                        var_el.set('type', elpar['type'])
                        readable = "yes"
                        if 'readable' in var_el: readable = elpar['readable']
                        var_el.set('readable', readable)
                        required = "yes"
                        if 'required' in elpar: required = elpar['required']
                        var_el.set('required', required)
                #print(ET.tostring(elem, encoding='utf8'))
                #print(ET.tostring(elem))

            # Add incoming and outgoing flows as child elements
            for incoming in element["incoming"]:
                ET.SubElement(elem, "incoming").text = incoming
            for outgoing in element["outgoing"]:
                ET.SubElement(elem, "outgoing").text = outgoing

            # Add event definition if it exists
            if "eventDefinition" in element and element["eventDefinition"]:
                event_def_type = element["eventDefinition"]
                # Create event definition element with a unique ID
                event_def_elem = ET.SubElement(elem, event_def_type)
                event_def_elem.set("id", f"{event_def_type}_{element['id']}")

        # Add flows
        for flow in transformed_process["flows"]:
            seq_flow = ET.SubElement(process_element, "sequenceFlow")
            seq_flow.set("id", flow["id"])
            seq_flow.set("sourceRef", flow["sourceRef"])
            seq_flow.set("targetRef", flow["targetRef"])

            # Add condition if it exists
            if flow["condition"]:
                seq_flow.set("name", flow["condition"])

        xml_string = ET.tostring(root, encoding="unicode")
        print("ALLES: ", xml_string)

        logger.info('create_bpmn_xml leave')

        return xml_string
